name: r2f_x3dh_e2e
description: "r2f_x3dh_e2e is a Rust to Flutter library enabling end-to-end encryption using the X3DH protocol, establishing shared secret keys for secure communication."
version: 0.0.2
homepage: https://github.com/hkk97/r2f_x3dh_e2e
repository: https://github.com/hkk97/r2f_x3dh_e2e

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.0.0-dev.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: 8.0.2
  integration_test:
    sdk: flutter

flutter:
