[package]
name = "rust_x3dh_e2e"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.16"
aes-gcm = "0.10.3"
hex = "0.4.3"
rand = "0.8.5"
lazy_static = "1.4"