// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.16.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(Uint8List, Uint8List) encryptWithHexStringKey(
        {required String sharedSecretKey,
        required String plaintext,
        dynamic hint}) =>
    RustLib.instance.api.encryptWithHexStringKey(
        sharedSecretKey: sharedSecretKey, plaintext: plaintext, hint: hint);

(Uint8List, Uint8List) encryptWithBytesKey(
        {required List<int> sharedSecretKey,
        required String plaintext,
        dynamic hint}) =>
    RustLib.instance.api.encryptWithBytesKey(
        sharedSecretKey: sharedSecretKey, plaintext: plaintext, hint: hint);

String decryptWithHexStringKey(
        {required String sharedSecretKey,
        required List<int> ciphertext,
        required List<int> iv,
        dynamic hint}) =>
    RustLib.instance.api.decryptWithHexStringKey(
        sharedSecretKey: sharedSecretKey,
        ciphertext: ciphertext,
        iv: iv,
        hint: hint);

String decryptWithBytesKey(
        {required List<int> sharedSecretKey,
        required List<int> ciphertext,
        required List<int> iv,
        dynamic hint}) =>
    RustLib.instance.api.decryptWithBytesKey(
        sharedSecretKey: sharedSecretKey,
        ciphertext: ciphertext,
        iv: iv,
        hint: hint);
